//このファイルは、ソースコードの文字エンコーディングに関係なく"UTF-8"で保存してください。

var Kw = {};

/*----------------------------------------------------------------------------------------
  common
----------------------------------------------------------------------------------------*/
//fineprint
//%jsdoc-toolkit%はJsDoc Toolkitサイトへのリンクに、%date%はドキュメントの作成日時に置き換えられます。
//Documentation generated by %jsdoc-toolkit% on %date%
//Kw.fineprint = "このドキュメントは%jsdoc-toolkit% (テンプレート:%template%)によって作成されました。 作成日：%date%";
Kw.fineprint = "Documentation generated by %jsdoc-toolkit% (template:%template%) on %date%";


/*----------------------------------------------------------------------------------------
  index.tmpl
----------------------------------------------------------------------------------------*/
Kw.index = {};
Kw.index.title = "APIリファレンス"; //JsDoc Reference


/*----------------------------------------------------------------------------------------
  overview.tmpl
----------------------------------------------------------------------------------------*/
Kw.overview = {};
Kw.overview.title = "概要"; //Overview
Kw.overview.author = "作成者"; //Author
Kw.overview.version = "バージョン"; //Version
Kw.overview.namespaces = "名前空間"; //Namespaces


/*----------------------------------------------------------------------------------------
  summary.tmpl
----------------------------------------------------------------------------------------*/
Kw.summary = {};
Kw.summary.title = "サマリ"; //Summary
Kw.summary.overview = "概要"; //Overview
Kw.summary.classIndex = "クラス一覧"; //Class Index
Kw.summary.fileIndex = "ファイル一覧"; //File Index
Kw.summary.caption = "クラス"; //Classes
Kw.summary.filterCaption = "検索..."; //Filter
Kw.summary.filterCaseSensitive = "大／小文字を区別"; //Case sensitive
Kw.summary.prefixMatch = "前方一致"; //Prefix match
Kw.summary.partialMatch = "部分一致"; //Partial match
Kw.summary.msgOpenConfigBtn = "検索設定を開く"; //Open search configs
Kw.summary.msgCloseConfigBtn = "検索設定を閉じる"; //Close search configs
Kw.summary.msgOpenClassBtn  = "クラスを展開する"; //Expand class members
Kw.summary.msgCloseClassBtn = "クラスを折りたたむ"; //Collapse class members


/*----------------------------------------------------------------------------------------
  classesindex.tmpl
----------------------------------------------------------------------------------------*/
Kw.classesIndex = {};
Kw.classesIndex.title = "クラス一覧"; //Class Index
Kw.classesIndex.caption = "クラス一覧"; //Class Index

Kw.classesIndex.msgOpenAllBtn  = "全てのクラス詳細を展開する"; //Expand all details
Kw.classesIndex.msgCloseAllBtn = "全てのクラス詳細を折りたたむ"; //Collapse all details
Kw.classesIndex.msgOpenBtn  = "詳細を展開する"; //Expand details
Kw.classesIndex.msgCloseBtn = "詳細を折りたたむ"; //Collapse details


/*----------------------------------------------------------------------------------------
  filesindex.tmpl
----------------------------------------------------------------------------------------*/
Kw.filesIndex = {};
Kw.filesIndex.title = "ファイル一覧"; //File Index
Kw.filesIndex.caption = "ファイル一覧"; //File Index
Kw.filesIndex.desc = "説明"; //Description
Kw.filesIndex.author = "作成者"; //Author
Kw.filesIndex.version = "バージョン"; //Version
Kw.filesIndex.location = "ロケーション"; //Location
Kw.filesIndex.defines = "クラス定義"; //Defines

Kw.filesIndex.msgOpenAllBtn  = "全てのファイル詳細を展開する"; //Expand all details
Kw.filesIndex.msgCloseAllBtn = "全てのファイル詳細を折りたたむ"; //Collapse all details
Kw.filesIndex.msgOpenBtn  = "詳細を展開する"; //Expand details
Kw.filesIndex.msgCloseBtn = "詳細を折りたたむ"; //Collapse details

/*----------------------------------------------------------------------------------------
  class.tmpl
----------------------------------------------------------------------------------------*/
Kw.clas = {};
Kw.clas.title = "クラスリファレンス"; //Class Reference
Kw.clas.typeNormal = "クラス"; //Class
Kw.clas.typeStaticClass = "静的クラス"; //Static Class
Kw.clas.typeAbstractClass = "抽象クラス"; //Abstract Class
Kw.clas.typeVirtualClass = "仮想クラス"; //Virtual Class
Kw.clas.typeNamespace = "名前空間"; //Namespace
Kw.clas.typeFunction = "関数"; //Function
Kw.clas.typeBuiltIn = "組み込み"; //Built-In
Kw.clas.typeInterface = "インタフェース"; //interface
Kw.clas.typeDeprecated = "【非推奨】"; //[Deprecated]
Kw.clas.collapseInherits = "他のクラスから継承したメンバを折りたたむ"; //Collapse inherited members
Kw.clas.hidePrivates = "プライベートメンバを隠す"; //Hide private members
Kw.clas.arrowLeft = "←"; //&larr;
Kw.clas.arrowRight = "→"; //&rarr;
Kw.clas.arrowUp = "↑"; //&uarr;

Kw.clas.linkFrame = "フレームあり"; //Frame
Kw.clas.linkNoFrame = "フレームなし"; //No Frame
Kw.clas.moveToSummaryTop = "概要トップへ移動"; //Move to summary top
Kw.clas.moveToDetailTop = "詳細トップへ移動"; //Move to detail top
Kw.clas.moveToSummary = "概要へ移動"; //Move to summary
Kw.clas.linkToConstructor = "コンストラクタ"; //Constructor
Kw.clas.linkToConstants = "定数"; //Constants
Kw.clas.linkToProperties = "プロパティ"; //Properties
Kw.clas.linkToMethods = "メソッド"; //Methods
Kw.clas.linkToEvents = "イベント"; //Events
Kw.clas.linkToSummaryTop = "概要トップ"; //Summary Top
Kw.clas.linkToDetailTop = "詳細トップ"; //Detail Top
Kw.clas.linkToPageTop = "ページトップ"; //Page Top
Kw.clas.linkToNamespaces = "名前空間"; //Namespaces
Kw.clas.linkToClasses = "クラス"; //Classes

Kw.clas.titleSummary = "概要"; //Summary
Kw.clas.titleDetail = "詳細"; //Detail
Kw.clas.captionConstructor = "コンストラクタ"; //Constructor
Kw.clas.captionConstants = "定数"; //Constants
Kw.clas.captionProperties = "プロパティ"; //Properties
Kw.clas.captionMethods = "メソッド"; //Methods
Kw.clas.captionEvents = "イベント"; //Events
Kw.clas.captionNamespaces = "名前空間"; //Namespaces
Kw.clas.captionClasses = "クラス"; //Classes

Kw.clas.captionInheritedConstants = "継承した定数"; //Inherited constants
Kw.clas.captionInheritedProperties = "継承したプロパティ"; //Inherited properties
Kw.clas.captionInheritedMethods = "継承したメソッド"; //Inherited methods
Kw.clas.captionInheritedEvents = "継承したイベント"; //Inherited events

//%class-alias%はクラスのネームパスに置き換えられます。
Kw.clas.defaultConstructorDesc = "新しい%class-alias%オブジェクトを作成する。";
Kw.clas.defaultAbstractConstructorDesc = "このコンストラクタから%class-alias%クラスのインスタンスを作成してはならない。";

Kw.clas.description = "説明"; //Description
Kw.clas.namespace = "名前空間"; //Namespace
Kw.clas.inheritance = "継承関係"; //Inheritance
Kw.clas.file = "定義"; //Defined in
Kw.clas.author = "作成者"; //Author
Kw.clas.parameters = "引数"; //Parameters
Kw.clas.optional = "省略可"; //Optional
Kw.clas.propDefault = "初期値"; //Default
Kw.clas.paramDefault = "デフォルト"; //Default
Kw.clas.deprecated = "非推奨"; //Deprecated
Kw.clas.since = "導入Ver."; //Since
Kw.clas.exception = "例外"; //Throws
Kw.clas.returns = "戻り値"; //Returns
Kw.clas.requires = "依存"; //Requires
Kw.clas.see = "関連項目"; //See
Kw.clas.constantValue = "定数値"; //value
Kw.clas.version = "バージョン"; //Version
Kw.clas.example = "サンプル"; //Example
Kw.clas.origin = "継承元"; //Origin
Kw.clas.interfaces = "インタフェース"; //Interfaces;
Kw.clas.interfacesFromAugments = "継承したインタフェース"; //From inheriting classes
Kw.clas.implementers = "実装クラス"; //Implementers
Kw.clas.todo = "ToDo"; //ToDo
Kw.clas.propProperties = "プロパティ"; //Properties
Kw.clas.examplePlain = "プレインテキスト"; //Plain text
Kw.clas.exampleHilited = "ハイライト"; //Hilited
Kw.clas.srcLink = "ソースコードを表示"; //Show source code

/*----------------------------------------------------------------------------------------
  others
----------------------------------------------------------------------------------------*/
//HTML 言語指定
Kw.lang = "ja";

//サマリ化処理で文の区切りとして使用される正規表現。
Kw.summarizeRegExp = /([\w\W]+?[.。])\s/i;

