//Save this file by "UTF-8" regardless of the character encoding of the source code.

var Kw = {};

/*----------------------------------------------------------------------------------------
  common
----------------------------------------------------------------------------------------*/
//fineprint
//%jsdoc-toolkit% is replaced to URL of JsDoc Toolkit official site, %date% is replaced to the date that document created.
Kw.fineprint = "Documentation generated by %jsdoc-toolkit% (template:%template%) on %date%";


/*----------------------------------------------------------------------------------------
  index.tmpl
----------------------------------------------------------------------------------------*/
Kw.index = {};
Kw.index.title = "API Reference";


/*----------------------------------------------------------------------------------------
  overview.tmpl
----------------------------------------------------------------------------------------*/
Kw.overview = {};
Kw.overview.title = "Overview";
Kw.overview.author = "Author";
Kw.overview.version = "Version";
Kw.overview.namespaces = "Namespaces";


/*----------------------------------------------------------------------------------------
  summary.tmpl
----------------------------------------------------------------------------------------*/
Kw.summary = {};
Kw.summary.title = "Summary";
Kw.summary.overview = "Overview";
Kw.summary.classIndex = "Class Index";
Kw.summary.fileIndex = "File Index";
Kw.summary.caption = "Classes";
Kw.summary.filterCaption = "search...";
Kw.summary.filterCaseSensitive = "Case sensitive";
Kw.summary.prefixMatch = "Prefix";
Kw.summary.partialMatch = "Partial";
Kw.summary.msgOpenConfigBtn = "Open search configs";
Kw.summary.msgCloseConfigBtn = "Close search configs";
Kw.summary.msgOpenClassBtn  = "Expand class members";
Kw.summary.msgCloseClassBtn = "Collapse class members";


/*----------------------------------------------------------------------------------------
  classesindex.tmpl
----------------------------------------------------------------------------------------*/
Kw.classesIndex = {};
Kw.classesIndex.title = "Class Index";
Kw.classesIndex.caption = "Class Index";

Kw.classesIndex.msgOpenAllBtn  = "Expand all";
Kw.classesIndex.msgCloseAllBtn = "Collapse all";
Kw.classesIndex.msgOpenBtn  = "Expand details";
Kw.classesIndex.msgCloseBtn = "Collapse details";


/*----------------------------------------------------------------------------------------
  filesindex.tmpl
----------------------------------------------------------------------------------------*/
Kw.filesIndex = {};
Kw.filesIndex.title = "File Index";
Kw.filesIndex.caption = "File Index";
Kw.filesIndex.desc = "Description";
Kw.filesIndex.author = "Author";
Kw.filesIndex.version = "Version";
Kw.filesIndex.location = "Location";
Kw.filesIndex.defines = "Defines";

Kw.filesIndex.msgOpenAllBtn  = "Expand all";
Kw.filesIndex.msgCloseAllBtn = "Collapse all";
Kw.filesIndex.msgOpenBtn  = "Expand details";
Kw.filesIndex.msgCloseBtn = "Collapse details";


/*----------------------------------------------------------------------------------------
  class.tmpl
----------------------------------------------------------------------------------------*/
Kw.clas = {};
Kw.clas.title = "Class Reference";
Kw.clas.typeNormal = "Class";
Kw.clas.typeStaticClass = "Static Class";
Kw.clas.typeAbstractClass = "Abstract Class";
Kw.clas.typeVirtualClass = "Virtual Class";
Kw.clas.typeNamespace = "Namespace";
Kw.clas.typeFunction = "Function";
Kw.clas.typeBuiltIn = "Built-In ";
Kw.clas.typeInterface = "Interface";
Kw.clas.typeDeprecated = "Deprecated ";
Kw.clas.collapseInherits = "Collapse inherited members";
Kw.clas.hidePrivates = "Hide private members";
Kw.clas.arrowLeft = "&larr;";
Kw.clas.arrowRight = "&rarr;";
Kw.clas.arrowUp = "&uarr;";

Kw.clas.linkFrame = "Frame";
Kw.clas.linkNoFrame = "No Frame";
Kw.clas.moveToSummaryTop = "Move to summary top";
Kw.clas.moveToDetailTop = "Move to detail top";
Kw.clas.moveToSummary = "Move to summary";
Kw.clas.linkToConstructor = "Constructor";
Kw.clas.linkToConstants = "Constants";
Kw.clas.linkToProperties = "Properties";
Kw.clas.linkToMethods = "Methods";
Kw.clas.linkToEvents = "Events";
Kw.clas.linkToSummaryTop = "SummaryTop";
Kw.clas.linkToDetailTop = "DetailTop";
Kw.clas.linkToPageTop = "PageTop";
Kw.clas.linkToNamespaces = "Namespaces";
Kw.clas.linkToClasses = "Classes";

Kw.clas.titleSummary = "Summary";
Kw.clas.titleDetail = "Detail";
Kw.clas.captionConstructor = "Constructor";
Kw.clas.captionConstants = "Constants";
Kw.clas.captionProperties = "Properties";
Kw.clas.captionMethods = "Methods";
Kw.clas.captionEvents = "Events";
Kw.clas.captionNamespaces = "Namespaces";
Kw.clas.captionClasses = "Classes";

Kw.clas.captionInheritedConstants = "Inherited constants";
Kw.clas.captionInheritedProperties = "Inherited properties";
Kw.clas.captionInheritedMethods = "Inherited methods";
Kw.clas.captionInheritedEvents = "Inherited events";

//%class-alias% is replaced to Namepath of the class.
Kw.clas.defaultConstructorDesc = "Create a new instance of %class-alias%.";
Kw.clas.defaultAbstractConstructorDesc = "You can not create instance of %class-alias% from this constructor.";

Kw.clas.description = "Description";
Kw.clas.namespace = "Namespace";
Kw.clas.inheritance = "Inheritance";
Kw.clas.file = "Defined in";
Kw.clas.author = "Author";
Kw.clas.parameters = "Parameters";
Kw.clas.optional = "Optional";
Kw.clas.propDefault = "Default";
Kw.clas.paramDefault = "Default";
Kw.clas.deprecated = "Deprecated";
Kw.clas.since = "Since";
Kw.clas.exception = "Throws";
Kw.clas.returns = "Returns";
Kw.clas.requires = "Requires";
Kw.clas.see = "See";
Kw.clas.constantValue = "Value";
Kw.clas.version = "Version";
Kw.clas.example = "Example";
Kw.clas.origin = "Inherit from";
Kw.clas.interfaces = "Interfaces";
Kw.clas.interfacesFromAugments = "From inheriting classes";
Kw.clas.implementers = "Implementers";
Kw.clas.todo = "ToDo";
Kw.clas.propProperties = "Properties";
Kw.clas.examplePlain = "Plain text";
Kw.clas.exampleHilited = "Hilited";
Kw.clas.srcLink = "Show source code";


/*----------------------------------------------------------------------------------------
  others
----------------------------------------------------------------------------------------*/
//HTML language attribute
Kw.lang = "en";

//Regular expression used as punctuation of sentence by processing of making to summary.
Kw.summarizeRegExp = /([\w\W]+?\.)[^a-z0-9_$]/i;

